### ISSUE TITLE
OSX-10.5 and deken

### ISSUE THREAD

**Issue by umlaeute** [pure-data/deken#106]
as mentioned in #88, there seem to be problems with deken on `OSX-10.5`

quoting @electrickery:

> MacOSX 10.5 is not supported by modern browsers, and the CA certificate store cannot be updated.
> So any HTTPS connection will fail. The problem is with the obsolete system, not deken.

**Comment by umlaeute** [comment]
i still do not understand what the problem is that you are facing.

what are the consequences of the certificates being outdated?
- you cannot *install* deken (and it's dependencies)?
- you cannot `deken upload` libraries?

if it's the 2nd, you can still create the library packages on the 10.5 machine (using `deken package`) and then upload them on another machine.

**Comment by electrickery** [comment]
It is installing deken on 10.5 that is the problem. I might ignore the warnings, but it would probably complain everytime I use the (not very) secure connection. So now I build and package on 10.5 and use deken on another (Linux) machine to sign and upload. Same procedure for Windows and Raspbian. 
I consider MacOSX 10.5 as too old for secure internet access. That is why I didn't create the issue here.

**Comment by umlaeute** [comment]
i see.

anyhow, you can use `deken package` on your linux machine with a directory containing binaries (produced on w32, OSX-10.5, raspbian or whatever), to create a "proper" deken-package (following the naming standards).

**Comment by danomatika** [comment]
I'd recommend adding platform-based info like this to the readme aka "Using Deke on an old version of OS X ..." etc
