### ISSUE TITLE
prompt users for global/user/application folders

### ISSUE THREAD

**Issue by porres** [pure-data/deken#144]
Pd has 3 Standard Paths that it searches for externals.

Seems like 'deken' now prompts for the user-specific folder first, by default, then moves on if it's not there. Next option is the Global folder, and finally the application folder.

Anyway, there's been a discussion if deken should create folders if they doesn't exist; see here: https://github.com/pure-data/deken/issues/143

And also another discussion about remembering the last chosen folder when Pd restarts (see https://github.com/pure-data/deken/issues/140 )

This issue I'm opening requests that yet another feature is added. Somehow, I'd like deken to offer these 3 Standard Paths it already searches for, then create them if they don't exist and remember the last option between restarts.

But if the user wants to choose a different Standard Path folder, deken should offer the 3 options again, then create the folder if it doesn't exist.

well, application specific is always there and created, we're talking about creating the User Specific or the Global folders only.

thanks

**Comment by reduzent** [comment]
There is no point in offering the global or application specific folder as a destination if the current user doesn't have permissions to write there.

**Comment by porres** [comment]
apparently, you mean to say there's no permission to write in the app/global folder in linux, right?

Well, it's not the same for other operating systems...

**Comment by reduzent** [comment]
Well, I don't know about Pd.app on Mac, but I'm confident that as user you can't write to /Library. On Windows (>=7), you need Admin privilges to write to the system-wide %ProgramFiles%. However, it's possible to install applications to a user specific %ProgramFiles%, where the user obviously has permissions to write to (without admin). But since you're talking about folders that do not yet exist, we can focus on global and user specific search paths. Since I still believe that the global search path is not writable by normal user on any platform, we're left with the user specific search paths. #143 addresses exactly this and creates them, if the user choses so.

So I don't see what's left to be created.

**Comment by porres** [comment]
It lets you install basically anywhere in Mac OS, in the application folder, in the user folder, in the global folder... I'm actually amazed there are all these issues elsewhere...

<img width="819" alt="screen shot 2017-03-02 at 18 31 43" src="https://cloud.githubusercontent.com/assets/5360142/23527923/a080468a-ff76-11e6-8032-69f169fcb940.png">

**Comment by umlaeute** [comment]
unlikely to happen.

from a UI perspective, this would now require a dialog that offers multiple choices (basically all available search paths), rather than a simple `Yes/No/Cancel` dialog.
I'm rather unwilling to implement anything that requires us ressort to non-standard dialogs.

(you could come up with a mockup of how the UI would look like; keep in mind that the list of stdpaths is variable, and that from a Pd perspective there is no such thing like a "per-user" or "system-wide" search path: they are all the same; i definitely will not add code that hardcodes the semantics of certain paths)

**Comment by porres** [comment]
yes, it would require a new dialog

> 
you could come up with a mockup of how the UI would look like

so, you mean for further discussion, or is this resolved and not arguable anymore?

> from a Pd perspective there is no such thing like a "per-user" or "system-wide" search path: they are all the same

what do you mean? I figured that the global folder affected all Pd applications for all users, whereas the user folder affected only that user. And then, the application folder affects only that application.

**Comment by umlaeute** [comment]
Pd has simply a list of folders it searches. Some depend on some environment-variables (like `${HOME}` or `%AppDir%`) but it doesn't care whether these env-vars are the same for all users or all instances of Pd.

it just sees a list of paths and searches those.

**Comment by umlaeute** [comment]
ah, and i meant "for further discussion" (i missed that part due to the broken quoting).

nothing is "not arguable anymore"
(i still think it highly unlikely that *I* will implement this, and doubt that *I* would accept a PR for this; but i am not the only one in charge of deken)
