### ISSUE TITLE
updated != replaced

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#149]
When installing a different version of a package than what was installed before and both versions do not contain the same set of files, the resulting library folder ends up being a mix of files of both versions.

When installing a package, the resulting folder should only contain files from the last installed package.

**Comment by reduzent** [comment]
I was told by IOhannes, that Deken actually doesn't know about the archive's content and thus cannot delete the folder before extracting over it. What it currently does, it extracts the archive to whatever it is there.

This means a Deken package could contain anything, including many root level folders. Do we really want that? Wouldn't it make sense to restrict Deken packages to one root level folder and foldername = libraryname?

If the foldername=libraryname rule is enforced (I believe I am a proponent of such a rule), Deken could simply delete the folder named libraryname before extracting the archive.

**Comment by umlaeute** [comment]
i have (only) two reasons why the current behaviour is not so bad:

## aggregate libraries
allowing multiple roots allows for aggregate libraries: a single download for all the things you ever need to (e.g.) work with arduino.

there are other ways to achieve/faciliate this:
- allow multiple downloads in one go (e.g. selecting multiple libraries before proceeding to download/install) via the deken-UI.
- `requirements.txt` or similar, to somehow declare dependencies on multiple packages, and download them in one go.

## extending libraries
multiple deken packages might want to install into the same root.
E.g. `Gem` comes with multiple extensions for image acquisition.
some of these only make sense if you have specific hardware, others are mutually exclusive with each others (at least: they might be).
All of them must reside besides the `Gem.dll` binary (which lives within the `Gem/` root folder).


## it's dead simple.
the current implementation is really simple.
there's no need to check whether a given deken-package contains only one root directory, and if so which one (in order to delete it).

also what happens, if the user cannot delete the directory? (e.g. the wise administrator installed `zexy` into  `%CommonProgramFiles%\Pd`, but the user wants to install a newer version into `%AppData%\Pd`...

**Comment by umlaeute** [comment]
random ideas:

- if the deken-package for `<library>` only contains a single root directory `<library>/`, we could reasonably assume that this is the canonical library and remove any existing instance.
this might lose any addons, but they might be incompatible anyhow and probably should be manually reinstalled.

- one could ask for confirmation before removing a directory (though this might create even more confusion)

**Comment by reduzent** [comment]
Personally, I favor your first idea. But how does Deken know that the archive contains?

**Comment by reduzent** [comment]
> also what happens, if the user cannot delete the directory? (e.g. the wise administrator installed zexy into %CommonProgramFiles%\Pd, but the user wants to install a newer version into %AppData%\Pd...

This issue is not specific to Deken. Without using Deken it is possible to have two versions of the same library installed. That's why I think, Deken doesn't have to deal with this. However, having a folder containing a merge of files from different archives _is_ Deken specific

**Comment by umlaeute** [comment]
note: the "first" idea (check for <library>/ within <library>-package) is not mutually exclusive with any of the rest.

**Comment by umlaeute** [comment]
`deken-0.3` removes the directory `<library>` before installing a `<library>.dek`. This can be turned off via the preferences.
