### ISSUE TITLE
Packages with “-” in its name fail to get added to the search paths.

### ISSUE THREAD

**Issue by Lucarda** [pure-data/deken#165]
This happen on the 3 main platforms, downloading any of these packages trigger the issue:

list-abs
pd-wavelet
la-kitchen

**Comment by danomatika** [comment]
Looks like the name needs to be escaped. Should be an easy fix.

**Comment by danomatika** [comment]
So the problem comes from splitting the deke string using the "-" character to get the package name. For packages with "-" in the name, only the first part of the name is set so the folder name check fails later on, ie. "list-abs-v0.1-20150529iem--externals.zip" -> name: "list" instead of "list-abs".

**Comment by danomatika** [comment]
@umlaeute @chr15m I'm trying `:;deken::parse_filename` but it's keeping the first version part "-v.01" of the filename in the pkgname. Is the zip filename wrong? Here's a test script:

~~~
proc parse_filename {filename} {
    set pkgname $filename
    set archs [list]
    set version ""
    if { [ regexp {(.*)-externals\..*} $filename _ basename] } {
        set pkgname $basename
        # basename <pkgname>[-v<version>-]?{(<arch>)}
        ## strip off the archs
        set baselist [split $basename () ]

        # get pkgname + version
        set pkgver [lindex $baselist 0]
        if { ! [ regexp "(.*)-(.*)-" $pkgver _ pkgname version ] } {
            set pkgname $pkgver
            set $version ""
        }
        # get archs
        foreach {a _} [lreplace $baselist 0 0] { lappend archs $a }
    }
    return [list $pkgname $version $archs]
}

set filename "list-abs-v0.1-20150529iem--externals.zip"
set parsed [parse_filename $filename]
set pkgname [lindex $parsed 0]

puts "filename: $filename"
puts "parse_filename: $parsed"
puts "pkgname: $pkgname"
~~~

I suppose a tangential answer to this problem is to drop the feature of deken adding to search paths in favor of the updated `declare -path` which search is user search paths already.

**Comment by Ant1r** [comment]
> drop the feature of deken adding to search paths in favor of the updated declare -path

+1

**Comment by Lucarda** [comment]
> So the problem comes from splitting the deken package string using the "-" character to get the package name. For packages with "-" in the name, only the first part of the name is set so the folder name check fails later on, ie. "list-abs-v0.1-20150529iem--externals.zip" -> name: "list" instead of "list-abs".

Is it possible to use the “**name of latest created folder**” in case the “folder **name check fails** ”?

**Comment by umlaeute** [comment]
no.
deken doesn't know anything about which folders get created.
you can also have a deken-package that contains multiple (parallel) folders

**Comment by Lucarda** [comment]
ok.
