### ISSUE TITLE
failing on a fresh install

### ISSUE THREAD

**Issue by porres** [pure-data/deken#210]
I'm trying to run a fresh install and get an error when I try to run deken for the first time.

it says 
" 
(defcompat)
  ^---------^
HyMacroExpansionError: expanding `defcompat': TypeError("'NoneType' object is not iterable",)
"

Here's my full attempt from scratch

<img width="923" alt="Screen Shot 2019-05-21 at 14 05 37" src="https://user-images.githubusercontent.com/5360142/58115945-89b17300-7bd1-11e9-9800-21f123511bb7.png">

**Comment by porres** [comment]
I couldn't really get deken to run by only typing "deken", so I tried ./deken instead and got the error. Anyway, one way or another, the instructions did not work for me

**Comment by umlaeute** [comment]
## installing

> I couldn't really get deken to run by only typing "deken"

please follow the *complete* [Getting Started](https://github.com/pure-data/deken/blob/master/developer/README.md#get-started) instructions. it mentions how to deal with "deken: command not found" errors.

## more info

what is your OS?
what's the output of the following commands?

~~~
~/.deken/virtualenv/bin/hy --version
~/.deken/virtualenv/bin/python --version
~~~


## fresh install
it seems that the screenshot you gave is not from a completely fresh installation. this is probably only because you tried to reproduce a clean installation (for the screenshot), but anyhow, your output shows no signs of installations (apart from the bootstrap script) - which indicates that the bootstrap script detected (and used) an existing installation of deken.

Unfortunately we don't have any `uninstall` method yet :-(

However, you should be able to trigger a re-installation by (re)running `deken install` (note to self: `deken install` is used for both self-installation and package installation, which is obviously a bug).

You should also be able to trigger a self-upgrade by (re)running `deken update`.

**Comment by umlaeute** [comment]
i've upgraded the implementation (and requirements) to hy-0.17, so the problem should be gone.

**Comment by porres** [comment]
hi, I had two computers and one of them was working, but I'm trying a fresh install again with a new computer and get the exact same issue again

**Comment by porres** [comment]
ok, here's what happens, I get the so called -bash deken command not found, which is addressed in here as you mentioned

https://github.com/pure-data/deken/blob/master/developer/README.md#get-started

more specifically it redirects us to here https://apple.stackexchange.com/questions/99788/os-x-create-a-personal-bin-directory-bin-and-run-scripts-without-specifyin/99838#99838

which should explain how to deal with it and it just says to add a line to "~/.bash_profile:"

thing is... I don't see this file. But I do see "~/.bash_history" and "~/.bash_sessions" though.

Anyway, so what I am doing (and I don't really know exactly what and how I'm doing it) is just download the source from git and run deken from inside the 'developer' folder. It seems to work just fine since I've uploaded many many packages so far, but I'd really like to be able to run deken in an "official" way...
