### ISSUE TITLE
Some uploaded packages are not findable

### ISSUE THREAD

**Issue by Lucarda** [pure-data/deken#248]
Hi,

I have uploaded manually (via puredata.info web interface) "abl_link~[v0.6]" for windows and linux a couple of hours ago and they still don't show up on searches.

I wonder what I did wrong?

I have uploaded all my pkgs this way and almost all are findable. Worth noting that my "earplug~" pkg (uploaded years ago) is also not findable.

How to fix this?

**Comment by umlaeute** [comment]
i don't know what you are doing.
but if you upload with the cmdline tool, it clearly says:

https://github.com/pure-data/deken/blob/c9cf81e563d75582a2b4e629d898ecf72c3a0141/developer/deken.hy#L1147

so why don't you just wait "up to 24 hours"?

> Worth noting that my "earplug~" pkg (uploaded years ago) is also not findable.

i would need more information in order to debug this (like: the exact link of the earplug upload you did that is not showing up)

**Comment by Lucarda** [comment]
> so why don't you just wait "up to 24 hours"?

Ok. the last months I uploaded stuff that went findable in less than 10min, I think I got used to that.

> i would need more information in order to debug this (like: the exact link of the earplug upload you did that is not showing up)

here:

http://puredata.info/Members/lucarda/software/earplug%5Bv0.0.extended%5D%28Windows-amd64-32%29%28Sources%29.dek/view

all my pkgs are in:

http://puredata.info/Members/lucarda/software/


Paranoias:

1 - Why is happening with "tilde" in name of pkg.
2 - Is it because there's no objectlist.txt?
3 - Is it because of case-sensitive differences in the name like:

In the web page:

```
Earplug~[V0.0.Extended](Windows-Amd64-32)(Sources).Dek
file path:
 earplug[v0.0.extended](Windows-amd64-32)(Sources).dek (ZIP archive 313Kb) 
```
 
4 - why I get abl_link~ result for v0.6 only for linux and if I search "abl_link*" (note the wildcard *) and nothing if search "abl_link~"

**Comment by umlaeute** [comment]
> Ok. the last months I uploaded stuff that went findable in less than 10min, I think I got used to that.

well, 10 minutes is just an extremely convenient "up to 24 hours".
i don't consider anything below 24h to be a problem.

> here:
> http://puredata.info/Members/lucarda/software/earplug%5Bv0.0.extended%5D%28Windows-amd64-32%29%28Sources%29.dek/view

shows up here (both within Pd, and one [deken.puredata.info](http://deken.puredata.info/search.html?libraries=earplug&objects=)

> 2 - Is it because there's no objectlist.txt?

no

> 3 - Is it because of case-sensitive differences in the name like

the displayed name (aka: description) is only for... display.
when searching for a library, the filename is taken into account.
so if the filename is "earplug[v0.0.extended](Windows-amd64-32)(Sources).dek" and the description is "fondingborg", then you will find it only with the "earplug" searchterm (but not when searching ~~"fondingborg"~~).

having said that: the search is case-insensitive, so "earplug" and "Earplug" are equivialent.

> 1 - Why is happening with "tilde" in name of pkg.

i'm not sure i can parse what you are saying.
however, the tilde **is** relevant.
so if your filename is `earplug[v0.0.extended](Windows-amd64-32)(Sources).dek` then this will **not** match a search for `earplug~` (even if the description says "Earplug~[V0.0.Extended](Windows-Amd64-32)(Sources).Dek" - see above)

4 - why I get abl_link~ result for v0.6 only for linux and if I search "abl_link*" (note the wildcard *) and nothing if search "abl_link~"

again: because your filename does not contain a `~` (but the description does).

this might be an issue with automatic normalisation for the filename, performed by the webserver (plone) when doing a manual upload.
it does not occur when using the deken cmdline tool.
you should be able to manually fix the filename via the webinterface (but make sure to change the filename, not just the description).

to preferred way is to use the deken cmdline tool.

**Comment by Lucarda** [comment]
Ok :)

The bug is in the web interface. It has eaten the "tilde" when picking the file.

I normaly create the zip and rename the file to .dek.

Log in to my folder and upload the file:

1 - give the name (copy the name from the Windows explorer) 

2 - select that file to upload (here somehow the "tilde" disappears)

Here is the screenshot of my files:

![deken1](https://user-images.githubusercontent.com/25239522/119584087-5bf1fc80-bd9e-11eb-9949-f29a2b1929dc.png)


------
-
-
-


I couldn't fix the file name via the web interface but I gave the Deken command line a try on Windows and it all went good.


:)

**Comment by Lucarda** [comment]
Now for the sake of completeness here is a screen-shot of the package uploaded with the command line and the filename also does not include the "tilde". But is findable.

![deken2](https://user-images.githubusercontent.com/25239522/119591808-a8910400-bdad-11eb-98e6-9d967390f8fb.png)


anyway I close this issue.

:)

**Comment by umlaeute** [comment]
ah well, the webinterface...

i just like to add: it doesn't even matter what the webinterface says that the "file path" is (although it *should* display the file-path correctly).

what *does* matter is the actual download URL (to be precise: the file-component - that is everything after the last `/` - of the URL)

the current download URL is http://puredata.info/Members/lucarda/software/abl_link%7E/0.6/abl_link%7E%5Bv0.6%5D%28Linux-amd64-32%29%28Linux-i386-32%29.dek which is the HTML-way of saying http://puredata.info/Members/lucarda/software/abl_link~/0.6/abl_link~[v0.6](Linux-amd64-32)(Linux-i386-32).dek - as you can see the file-component of the URL is `abl_link~[v0.6](Linux-amd64-32)(Linux-i386-32).dek` which is well formatted and therefore works.

hard to tell now what the original URLs were...

**Comment by Lucarda** [comment]
> hard to tell now what the original URLs were...

I think this is the only unfindable example that remains in my folder:

http://puredata.info/Members/lucarda/software/convolve%5Bv0.13%5D%28Windows-amd64-32%29%28Sources%29.dek/view

The issue did only happened for packages names ending with "tilde".

The "%7E" was not converted (or omitted) at upload time.

I'm pretty sure I uploaded the file accordingly to its name (as described above).

**Comment by umlaeute** [comment]
thanks for the example.

|  key | value |
|-------|---------|
| description | `convolve~[v0.13](Windows-amd64-32)(Sources).dek` |
| file path | `convolve[v0.13](Windows-amd64-32)(Sources).dek (ZIP archive 1673Kb) ` |
| (pretty) URL | http://puredata.info/Members/lucarda/software/convolve[v0.13](Windows-amd64-32)(Sources).dek |

so it's pretty obvious, that the `~` was munged away both in the URL and in the displayed file-path (with the former being the reason why deken thinks it's called "convolve" and not "convolve~").

So here's what I did to fix the name:
1. navigate to the containing folder http://puredata.info/Members/lucarda/software
2. switch to <kbd>contents</kbd>-view
3. select the `convolve~[v0.13](Windows-amd64-32)(Sources).dek` (using the tickbox)
4. click the <kbd>rename</kbd>-button at the bottom of the page
5. change the **New Short Name** to `convolve~[v0.13](Windows-amd64-32)(Sources).dek`
6. save

**Comment by Lucarda** [comment]
:)
