### ISSUE TITLE
fresh installed deken says I shall report: Self-installation of Deken failed.

### ISSUE THREAD

**Issue by ritsch** [pure-data/deken#254]
Here detailed description on bullseye  debian amd64: 

```
vrr@vrr2:~/ICE-VCH/vch/setup$ sudo apt install deken
...
vrr@vrr2:~/ICE-VCH/vch/setup$ deken --help
Self-installation of Deken failed.
Please paste any errors in the bug tracker at https://github.com/pure-data/deken/issues
```

So I did.

**Comment by umlaeute** [comment]
- this is somewhat a bug in the Debian packaging (and should actually be reported with `reportbug`; i know that the error says otherwise)
  - it's already fixed in deken-0.8.0 (though that doesn't really help you on bullseye)
- this is really a duplicate of #247 (just telling; i'm aware that the title probably doesn't indicate this)
- the quick workaround is to run `mkdir ~/.deken`
