### ISSUE TITLE
No deken or pd-deken package on Ubuntu 22.04

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#260]
The developer's manual mentions that Debian and derivative distributions deliver a deken package. Unfortunately, this does not seem true for Ubuntu 22.04

**Comment by umlaeute** [comment]
well yeah.
`hy` has been removed from Debian/testing (due to some problems with Python3.10), and in consequence from Ubuntu.

Since `deken` (the cmdline tool) uses `hy`, this means that `deken` has also been removed (including binary packages that don't directly depend on `hy`).

Once `hy` comes back, `deken` will also be part of whatever the Ubuntu release is then.

I don't think I want to update the docs everytime a package is removed from a distro.

**Comment by reduzent** [comment]
I see. Thanks for the info. I guess Ubuntu happened to be released at an unlucky moment.

**Comment by umlaeute** [comment]
fwiw, deken-0.9.2 has entered Debian/testing today, and Ubuntu/kinetic yesterday.
