### ISSUE TITLE
Downloading packages with long filenames fails on certain filesystems

### ISSUE THREAD

**Issue by reduzent** [pure-data/deken#261]
The package http://puredata.info/Members/porres/software/else/1.0-0_rc1-with_live_electronics_tutorial/else%5Bv1.0-0_rc1-with_live_electronics_tutorial%5D(Darwin-amd64-32)(Darwin-arm64-32)(Linux-amd64-32)(Linux-arm64-32)(Linux-armv6-32)(Linux-i386-32)(Windows-amd64-32)(Windows-i386-32).dek cannot be installed on my system with Deken. It simply says: `Download failed!`

The culprit seems to be the long filename of the package. My user home is using the ecrypt filesystem on top of ext4. The available filename length of 255 characters is reduced by the encryption of ecryptfs. The package mentioned above exceeds the maximum length.

The topic has been discussed here: 
https://lists.puredata.info/pipermail/pd-list/2022-04/131144.html

**Comment by umlaeute** [comment]
i guess the proper solution would be to rename the files on download.
there's no reason that we need to save them as `else[v1.0-0_rc1-with_live_electronics_tutorial](Darwin-amd64-32)(Darwin-arm64-32)(Linux-amd64-32)(Linux-arm64-32)(Linux-armv6-32)(Linux-i386-32)(Windows-amd64-32)(Windows-i386-32).dek](http://puredata.info/Members/porres/software/else/1.0-0_rc1-with_live_electronics_tutorial/else%5Bv1.0-0_rc1-with_live_electronics_tutorial%5D(Darwin-amd64-32)(Darwin-arm64-32)(Linux-amd64-32)(Linux-arm64-32)(Linux-armv6-32)(Linux-i386-32)(Windows-amd64-32)(Windows-i386-32).dek)`, a simple `else.1.zip` should do as well...

using the `.zip` suffix for instead of `.dek` will also make it easier for users to unzip the file manually if things went wrong.
otoh, keeping the `.dek` suffix might have advantages as:
- it is more consistent (the user only ever needs to know (if at all) about `.dek` files)
- drag'n'dropping the ZIP-files to the deken-window might not work.

**Comment by reduzent** [comment]
Cool. Thanks!
