### ISSUE TITLE
Deken / Pure Data 0.53.1 / RPi OS 11 32-bit weird issue

### ISSUE THREAD

**Issue by joe-rouen** [pure-data/deken#284]
Hello,
I have a weird issue with the integrated Deken function on Pure Data 0.53.1 under Raspberry Pi OS 11 32-bit.
I cannot test on my other computers, neither on GNU/Linux nor Windows, as for the time being I have no access to them.
On my RPi 400, I just moved from Pd 0.53.0 to 0.53.1 (both compilation from source then installation).

1. I wanted to update to the latest ELSE library (from 1.0.0 rc-1 to 1.0.0 rc-5) but the integrated Deken search engine is stating that: 
"La recherche de http://deken.puredata.info/search a donné 5 résultats
0 paquets utilisables trouvés (sur un total de 4 paquets).
Il semble qu'il n'y ait aucun paquet correspondant à votre architecture"
i.e. 5 results found but 0 usable package found and it seems no package is available for your architecture!

Well, I went directly to http://deken.puredata.info/search and here I got:
else[v1.0-0_rc5-with_live_electronics_tutorial](Darwin-amd64-32)(Darwin-arm64-32)(Linux-amd64-32)(Linux-arm64-32)(Linux-armv7-32)(Windows-amd64-32).dek
So, it should be available for my Linux-armv7-32!

2. The same apply at least to the IemLib and Pdogg libraries but not to all my libraries already installed on my RPi 400, like the Cyclone one which is still available through Deken.

Any idea what is happening?
Thank you

**Comment by Ant1r** [comment]
Try this:
- open Deken's preference (via the "Plus..." button)
- uncheck "Hide foreign architectures" (in French: "Cacher les autres architectures")

Now you'll see all the existing architectures for the library you'll search. Select a version containing `armv7` architecture and you should be done.

The fact is that a library compiled for `armv6` will work also on `armv7`, but Deken only shows (by default) your current architecture, which is `armv7`...

**Comment by joe-rouen** [comment]
@Ant1r Thank you so much. You saved my day!
in Deken 0.9.4 Preferences, I have changed Default Platform: Linux-armv6-32 to User Defined Platform: Linux-armv7-32.
And now the situation is back to business as usual. Great!

Side comment: Linux-armv6-32 was working well few weeks ago. So I suspect some changes have been done in the way Deken is managing the platforms.

**Comment by umlaeute** [comment]
> Side comm
ent: Linux-armv6-32 was working well few weeks ago. So I suspect some changes have been done in the way Deken is managing the platforms.

no.

the issue is mainly with how your Pd binary was compiled.

- Raspbian traditionally targetted `armv6` (or rather a subset thereof, with hardfloat support), so the Pd binaries installed from the Raspbian repositories typically claim to be `armv6` only. Since Pd has no code in place to check whether the actual CPU is capable of running `armv7` instructions, so deken errs on the safe side, so only `Linux-armv6-32` binaries are shown.
- Conversely, the Debian binaries for the armhf platform target `armv7`, which is guaranteed to be compatible with `armv6` so both `Linux-armv6-32` and `Linux-armv7-32` binaries will be shown.
- If you build Pd yourself, you probably will get an `armv7` binary (but with the right flags, you can get an `armv6` binary as well...)

This is a duplicate of #206
