### ISSUE TITLE
Use .zip on Windows and multi-platforms and .tar.gz on OSX-only and Linux-only platforms to preserve symlinks.

### ISSUE THREAD

**Issue by chr15m** [pure-data/deken#9]
Feature request by @electrickery

**Comment by electrickery** [comment]
Hi Chris,

Following this email I tried it bu upgrading deken and attempt to upload
cyclone. The upload succeeded, but still as a zip. It also requests a
GPG passphrase. Should I have prepared the key stuff, or wants it to
generate everything on the fly?

Greetings,

Fred Jan

On 2015-06-13 04:25 PM, Chris McCormick wrote:
> Feature request by @electrickery <https://github.com/electrickery>
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pure-data/deken/issues/9>.
> 


fjkraan@var:~/pd-externals$ ~/bin/deken upload ./cyclone -v 0.1-alpha57
Deken 0.1
Packaging into ./cyclone-v0.1-alpha57-(Linux-amd64-64)-externals.zip
Uploading ./cyclone-v0.1-alpha57-(Linux-amd64-64)-externals.zip
Uploading to
http://puredata.info/Members/fjkraan/cyclone-v0.1-alpha57-(Linux-amd64-64)-externals.zip.sha256
Uploading to
http://puredata.info/Members/fjkraan/cyclone-v0.1-alpha57-(Linux-amd64-64)-externals.zip
Attempting to GPG sign ./cyclone-v0.1-alpha57-(Linux-amd64-64)-externals.zip
You need a passphrase to unlock the secret key for
user: Fred Jan Kraan <fjkraan@xs4all.nl> ID: D7C9F7456A6F788B
in order to sign ./cyclone-v0.1-alpha57-(Linux-amd64-64)-externals.zip
Enter GPG passphrase:
[GNUPG:] USERID_HINT D7C9F7456A6F788B Fred Jan Kraan <fjkraan@xs4all.nl>
[GNUPG:] NEED_PASSPHRASE D7C9F7456A6F788B D7C9F7456A6F788B 1 0
[GNUPG:] BAD_PASSPHRASE D7C9F7456A6F788B
gpg: no default secret key: bad passphrase
gpg: signing failed: bad passphrase

WARNING: Could not GPG sign the package.

**Comment by chr15m** [comment]
Hi Fred Jan,

The feature has not yet been developed, I just added your name to the issue so you will get a notification when it is done.

If you enter your correct passphrase for that key when prompted then it will sign with that key. If you want to use a different key put the key_id in the config file. If you don't want to sign the binary you can just ctrl-C at the passphrase part..

**Comment by electrickery** [comment]
Hi Chris,

> Hi Fred Jan,
> 
> The feature has not yet been developed, I just added your name to the
> issue so you will get a notification when it is done.
> 
> If you enter your correct passphrase for that key when prompted then it
> will sign with that key. If you want to use a different key put the
> key_id in the config file. If you don't want to sign the binary you can
> just ctrl-C at the passphrase part..

I have no problem signing, but I don't know to which secret key the
passphrase is referring. So I don't know the passphrase.
But if the feature is still in development, I'll wait until it is completed.

I did try creating keys within Enigmail/Thunderbird, but the presented
ID is different.

Another remark; If I let deken upload create the zip, it is even larger
than an uncompressed tar-file. As if compression is not enabled.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pure-data/deken/issues/9#issuecomment-111808690>.
> 

Greetings,

Fred Jan

**Comment by chr15m** [comment]
The feature is completed to the point that it works correctly. It seems like the problem is you don't know the passphrase for your default secret key in your GPG keyring. You can check the key ID that is shown "D7C9F7456A6F788B" against `gpg --list-keys`.

I'll check the large-zip issue.

**Comment by electrickery** [comment]
Hi Chris,

> The feature is completed to the point that it works correctly. It seems
> like the problem is you don't know the passphrase for your default
> secret key in your GPG keyring. You can check the key ID that is shown
> "D7C9F7456A6F788B" against |gpg --list-keys|.

When I execute 'gpg --list-keys' it doesn't list anything containing
'D7C9F7456A6F788B'. What would be proper settings to create a default
key used for signing?
> 
> I'll check the large-zip issue.
> 
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/pure-data/deken/issues/9#issuecomment-111974493>.
> 

Greetings,

Fred Jan

**Comment by umlaeute** [comment]
@electrickery the key-id as output by `gpg --list-keys` only contains 4 bytes, whereas the error message got 8 bytes. just use the last 8 characters (4 bytes) `6A6F788B` in the comparision.

also i find using `gpg --list-secret-keys` nicer when searching hrough my own keys (as it only lists the keys that i can sign with)

**Comment by electrickery** [comment]
Hi IOhannes,

Thanks for the info. Looking at just the last 4 bytes, there is a
matching key.

With that I managed to upload and sign, resulting in an .zip.asc file. I
suppose it works :-).

Fred Jan
